apiVersion: v1
kind: Pod
metadata:
  name: redis-poddef
  labels:
    name: redis-pod
    app: vote-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379


